---

- hosts: all
  become: true
  tasks:

  
    - name: install apache2 and php package
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
  #or when: ansible_distribution in ["Debian", "Ubuntu"]

## ansible-playbook --ask-become-pass Install_apache.yaml

# if one of servers is Centos then at the result you see "skipp=3" because can not run apt and if you dont use "when: ansible_distribution == "Ubuntu" " then at the result you see "failed=1"

    - name: install httpd and php on CentOS
      yum:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"
      
    - name: Restart and enable service httpd on CentOS
      service:
        name: 
          - httpd
          - php
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        port: 80
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"
