---

- hosts: all
  become: true
  tasks:

    - name: update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
  #or when: ansible_distribution in ["Debian", "Ubuntu"]
  
    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"


## ansible-playbook --ask-become-pass Install_apache.yaml

# if one of servers is Centos then at the result you see "skipp=3" because can not run apt and if you dont use "when: ansible_distribution == "Ubuntu" " then at the result you see "failed=1"

    - name: update repository index
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"
  #or when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install apache2 package
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"

    - name: add php support for apache
      yum:
        name: php
        state: latest
      when: ansible_distribution == "CentOS"
