---
- hosts: all
  become: true
  pre_tasks:

    - name: install update (CentOS)
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribute == CentOS

    - name: install update (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribute == Ubuntu
---
- host: web_servers
  become: true
  task:

    - name: install apache2 and php package
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
  #or when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install apache2 and php package
      tags: apache,httpd,centos
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"
      
    - name: Restart and enable service httpd, in all cases
      ansible.builtin.service:
        name: 
          - httpd
          - php
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        port: 80
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"

    - name: copy default html file for site
      tages: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
---
- host: db_servers
  become: true
  task:

    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      tags: ubuntu,mariadb,db
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Restart and enable service mariadb in all cases
      ansible.builtin.service:
        name: mariadb
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        port: 3306 
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"
---
- host: file_servers
  become: true
  task:

    - name: install samba package (CentOS)
      tags: samba
      package:
        name: samba
        state: latest

    - name: Restart and enable service samba in all cases
      ansible.builtin.service:
        name: samba
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        ports:
          - 445
          - 139
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"

##"tags: always": it means all tags and run this section with all tags
