- name: Install apache2 and php on (Ubuntu)
  tags: ubuntu,apache,apache2
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribute == "Ubuntu"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Restart apache2 service
  tags: ubuntu,apache,apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: ansible_distribute == "Ubuntu"
---
- name: Install httpd and php on (CentOS)
  tags: centos,apache,httpd
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribute == "CentOS"

- name: Change e-mail address for admin
  tags: apache,httpd,centos
  lineinfile:
    path: /etc/httpd/config/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin Somebody@somewhere.net
  when: ansibe_distribution == "CentOS"
  register: httpd

- name: copy default html file for site
  tags: apache,apache2,httpd
    copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Restart httpd service
  tags: centos,apache,httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: ansible_distribute == "CentOS"

