- name: Install apache and php 
  tags: apache,httpd,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: copy default html file for site
  tags: apache,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Change e-mail address for admin
  tags: apache,httpd,centos
  lineinfile:
    path: /etc/httpd/config/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin Somebody@somewhere.net
  when: ansibe_distribution == "CentOS"
  notify: restart_apache 

