---
- hosts: all
  become: true
  pre_tasks:

    - name: install update (CentOS)
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribute == CentOS

    - name: install update (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribute == Ubuntu
---
- hosts: all
  become: true
  tasks:

    - name: Create user
      tags: always
      user:
        name: alex
        groups: root 

    - name: add ssh key for Alex
      tags: always
      authorized_key:
        user: alex
        key: "ssh-id AAAAC......."

    - name: add sudoers file for Ales
      tags: always
      copy:
        src: sudoer_alex
        dest: /etc/sudoers.d/alex
        owner: root
        group: root
        mode: 06440

---
- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicrop.com/terraform/0.12.28/terraform_0.12.28_linux_md64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
---
- host: web_servers
  become: true
  task:

    - name: install apache2 and php on Ubuntu
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
  #or when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install httpd and php oc CentOS
      tags: apache,httpd,centos
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"
      
    - name: Change e-mail address for admin
      tags: apache,httpd,centos
      lineinfile:
        path: /etc/httpd/config/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin Somebody@somewhere.net
      when: ansibe_distribution == "CentOS"
      register: httpd

    - name: Restart and enable service httpd on CentOS
      tags: apache,centos,httpd
      service:
        name: 
          - httpd
          - php
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        port: 80
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
---
- host: db_servers
  become: true
  task:

    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      tags: ubuntu,mariadb,db
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Restart and enable service mariadb onCentOS
      service:
        name: mariadb
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        port: 3306 
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"
---
- host: file_servers
  become: true
  task:

    - name: install samba package (CentOS)
      tags: samba
      package:
        name: samba
        state: latest

    - name: Restart and enable service samba on CentOS
      service:
        name: samba
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        ports:
          - 445
          - 139
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"

##"tags: always": it means all tags and run this section with all tags
