- name: Install mariadb server (CentOS)
  tags: db,mariadb,centos
  yam:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb server (Ubuntu)
  tags: mariadb,db,ubuntu
  apt:
    name: mariadb-server
    state: latest
    when: ansible_distribute == "Ubuntu"

